# SITE CONFIGURATION
title: Lifa # your site title
author: Hippolyte-Fayol Toulassi
description: Energy of the future
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lifa.co.za" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Lifa SA
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'About Lifa', link: '/about-lifa'}
  - {name: 'Our Businesses', link: '/business'}
  - {name: 'Sustainability', link: '/sustainability'}
  - {name: 'Career', link: '/career'}
  - {name: 'Investors', link: '/investors'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Energy of the future

hero_img: posts/lifa_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: kossit@lifa.co.za # email for form submission

twitter_username: fayolt # replace with your_twitter_username or comment to remove link from footer
github_username:  fayolt # replace with your_github_username or comment to remove link from footer
instagram_username: fayolito # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem

sass:
  sass_dir: _sass

exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
